name: Android Check Build

on: 
  push:
    paths: 
      - 'tmdbandroid/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: ktlint
        run: ./gradlew ktlint

      - name: Build Project
        run: ./gradlew assemble
